#!/bin/bash
set -ueo pipefail

USAGE="$(basename "$0") [dark|light]"

if [ $# -ge 1 ] && ([ "$1" = "-h" ] || [ "$1" = "--help" ]); then
    echo "${USAGE}"
    exit 0
fi

if [ $# -ge 1 ]; then
    if [ "${1}" = 'dark' ]; then
        COLORSCHEME='dark'
    else
        COLORSCHEME='light'
    fi
else
    COLORSCHEME="$(([ $(date +%k) -ge 7 ] && [ $(date +%k) -lt 18 ]) && echo light || echo dark)"
fi

echo "${COLORSCHEME}" > ~/.config/colorscheme

# update alacritty and k9s colorscheme on demand
rm -f ~/.config/k9s/skin.yml
if [ "${COLORSCHEME}" = 'light' ]; then
    # sed -i -e 's/^colors:.*/colors: *papercolor/' ~/.config/alacritty/alacritty.yml
    sed -i -e 's/^colors:.*/colors: *tokyoday/' ~/.config/alacritty/alacritty.yml
    # ln -s ~/.config/k9s/solarized_light.yml ~/.config/k9s/skin.yml
    ln -s ~/.config/k9s/tokyonight_day.yml ~/.config/k9s/skin.yml
else
    # sed -i -e 's/^colors:.*/colors: *nord/' ~/.config/alacritty/alacritty.yml
    sed -i -e 's/^colors:.*/colors: *tokyostorm/' ~/.config/alacritty/alacritty.yml
    ln -s ~/.config/k9s/nord.yml ~/.config/k9s/skin.yml
fi

# tmate setenv -g COLORSCHEME "${COLORSCHEME}"
# tmate source ~/.tmux.conf
tmux setenv -g COLORSCHEME "${COLORSCHEME}"
tmux source ~/.tmux.conf

