#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Display date in dwm's status line


from Xlib.display import Display
from datetime import datetime
import time
import os

# SYM_M = u'📧'
SYM_M = u'M'
# TIMEFORMAT = u' 📆%V, %a %b %e %T %Y '
TIMEFORMAT = u' W%V, %a %b %e %T %Y '
MQ = os.path.expanduser(os.path.expandvars('~/.msmtp.queue/'))
R = Display().screen().root

while True:
	m = ''
	f = list(os.listdir(MQ))
	if len(f):
		m = u' %d%s' % (len(f) / 2, SYM_M)
	R.set_wm_name(m + datetime.now().strftime(TIMEFORMAT))
	R.get_wm_name()
	time.sleep(1)
