#!/bin/sh
set -e
set -u

SHORTCUTS="
!ade
!g
!gi
!github
!leo
!maps
!osm
!thesaurus
!thesaurusde
!w
!wde
"

query="$(echo "${SHORTCUTS}" | dmenu)"
[ -n "${query}" ] && x-www-browser "https://duckduckgo.com/?q=${query}"
