#!/bin/sh
# enable-naturalscrolling
#  Enable natural scrolling for all registered pointers
#
# Depends: libinput - all input devices should be managed through libinput!
#
# Copyright (C) 2016 Jan Christoph Ebersbach
#
# http://www.e-jc.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

set -u
set -e

# list all input devices: xinput
# list properties of input device: xinput list-props <ID>
# set property: xinput set-prop <ID> <PROP_ID> <VALUE>
xinput | awk -F = '/slave  pointer/ {gsub(/\s.*/, "", $2); print($2)}' | while read id; do
    prop_id="$(xinput list-props "${id}" | grep 'Natural Scrolling Enabled (' | sed -e 's/.*(\([0-9]*\)):.*/\1/')"
    if [ -n "${prop_id}" ]; then
        xinput set-prop "${id}" "${prop_id}" 1
    fi
done
