#!/bin/bash
# wrapper around feh execution from a file manager to support view all images in
# the current directory
cmd=(exec feh)
if [ $# -eq 1 ]; then
    dir=
    if [ ! -d "${1}" ]; then
        dir="$(dirname "${1}")"
        cmd+=(--start-at "${1}")
    else
        dir="${1}"
    fi
    cmd+=(--magick-timeout 0.5 "${dir}")
else
    cmd+=("${@}")
fi
"${cmd[@]}"
