#!/bin/bash

echo "Running fixxmodmap..."

# clear configuration
setxkbmap -option

# look at /usr/share/X11/xkb/rules/base.lst
# for grp:ctrls_toggle see also https://bugs.freedesktop.org/show_bug.cgi?id=15843
# /usr/share/X11/xkb/symbols/group
if [ -e "${HOME}/.Xkbmap" ]; then
    setxkbmap $(cat "${HOME}/.Xkbmap")
fi
if [ -e "${HOME}/.Xmodmap" ]; then
    xmodmap "${HOME}/.Xmodmap"
fi


# set screensaver to start after 10 minutes
xset s $((10*60))
xset s on

# set repeat settings
xset r rate 350 40

# turn bell off
xset b off

# update mouse pointer
xsetroot -cursor_name left_ptr

touchpad

naturalscrolling
