#!/bin/bash

echo "Running fixxmodmap..."

# xmodmap -e "add shift = Shift_L"
# xmodmap -e "add shift = Shift_R"

# xmodmap -e "add lock = Caps_Lock"

# #xmodmap -e "keycode 66 = Caps_Lock"
# #xmodmap -e "add lock = Caps_Lock"
# #xmodmap -e "remove lock = Caps_Lock"
# #xmodmap -e "add Shift = Caps_Lock"
# #xmodmap -e "keycode 66 = Multi_key"

# #xmodmap -e 'keycode 66 = Caps_Lock'
# #xmodmap -e 'add lock = Caps_Lock'
# xmodmap -e 'remove lock = Caps_Lock'
# xmodmap -e 'keycode 66 = Multi_key'

# xmodmap -e "add control = Control_L"
# xmodmap -e "add control = Control_R"

# xmodmap -e "add mod1 = Alt_L"
# xmodmap -e "add mod1 = Meta_L"

# xmodmap -e "add mod2 = Num_Lock"

# xmodmap -e "add mod4 = Super_L"
# xmodmap -e "add mod4 = Hyper_L"

# xmodmap -e "add mod5 = Mode_switch"
# xmodmap -e "add mod5 = ISO_Level3_Shift"

# clear configuration
setxkbmap -option
# look at /usr/share/X11/xkb/rules/base.lst
# for grp:ctrls_toggle see also https://bugs.freedesktop.org/show_bug.cgi?id=15843
# /usr/share/X11/xkb/symbols/group
setxkbmap $(cat ~/.Xkbmap)

xmodmap ~/.Xmodmap

# set screensaver to start after 10 minutes
xset s $((10*60))
xset s on

# set repeat settings
xset r rate 350 40

# turn bell off
xset b off

# update mouse pointer
xsetroot -cursor_name left_ptr

naturalscrolling
