#!/bin/sh
#xmodmap -e 'keycode 66 = Caps_Lock'
#xmodmap -e 'add lock = Caps_Lock'
#xmodmap -e 'remove lock = Caps_Lock'
#xmodmap -e "add Shift = Caps_Lock"
#xmodmap -e 'keycode 66 = Multi_key'

#setxkbmap -option compose:caps -model pc104 -layout us,de -variant ,
setxkbmap -option compose:caps -layout us -variant colemak
xmodmap -e 'keycode 135 = Super_L'

xset r rate 350 30
