#!/bin/bash
if [ -e ".envrc" ] && [ -e "shell.nix" ]; then
    echo "ERROR: can't set up nix shell, files already exist: .envrc, shell.nix" 1>&2
    exit 1
fi

cat > .envrc <<EOF
use nix
EOF

cat > shell.nix <<EOF
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  buildInputs = [
    # pkgs.XYZ
  ];
}
EOF
