#!/bin/bash
# Open a shell in a UCS docker image.
# List of tags: https://hub.docker.com/r/univention/ucs-generic-amd64/tags
# Usage: run-ucs [DOCKER-TAG]
set -e
set -u

export IMAGE="nixos/nix"
export CMD="/bin/sh"

exec run-ucs "$@"
