#!/bin/sh
set -e
set -u

VERSION="${1:-latest}"
IMAGE="univention/ucs-generic-amd64"

echo "Running ${IMAGE}:${VERSION}"

if ! docker image inspect "${IMAGE}:${VERSION}" &>/dev/null; then
    docker image pull "${IMAGE}:${VERSION}"
fi

exec docker run -t -i --mount type=bind,src=$PWD,dst=/src "${IMAGE}:${VERSION}" /bin/bash
