#!/bin/sh
# Open a shell in a UCS docker image.
# List of tags: https://hub.docker.com/r/univention/ucs-generic-amd64/tags
# Usage: run-ucs [DOCKER-TAG]
set -e
set -u

VERSION="${VERSION:-latest}"
IMAGE="${IMAGE:-univention/ucs-generic-amd64}"
CMD="${CMD:-/bin/bash}"
UID="${UID:-$(id -u)}"
GID="${GID:-$(id -g)}"

echo "Running ${IMAGE}:${VERSION}"
echo "with UID ${UID} and GID ${GID}"

if ! docker image inspect "${IMAGE}:${VERSION}" &>/dev/null; then
    docker image pull "${IMAGE}:${VERSION}"
fi

exec docker run -t -i --rm -u "${UID}:${GID}" -w /app --mount "type=bind,src=$PWD,dst=/app" "${IMAGE}:${VERSION}" "${CMD}" "$@"
