#!/bin/sh
MAILDIR=~/Documents/Data/backup/Mail/

cd $MAILDIR

#echo -n "+ "

for file in $(find . -type d)
do
    #box=$(basename "$file")
    box="$file"
    if [ -d $file/new  -a -d $file/cur -a -d $file/tmp ]
    then
        echo -n "\"+${box:2:${#box}}\" "
    fi
done
