#!/bin/sh
# dwm startup script

# extend the PATH variable with ~/bin
if [[ -e "${HOME}/bin" ]]; then
	export PATH="$HOME/bin:$PATH"
fi

export LANG=en_US.UTF-8
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus

# set wallpaper
#display -window root $HOME/wallpaper0.jpg
#(DISPLAY=${DISPLAY}.1 display -window root $HOME/wallpaper1.jpg) &
#DISPLAY=${DISPLAY}.1 habak -hi $HOME/wallpaper1.jpg -mc 90,90,90,200 -mh 20 -mp 10,850 -mf /usr/share/fonts/truetype/msttcorefonts/Trebuchet_MS.ttf -ht "`verse`"
#habak -hi $HOME/wallpaper0.jpg -mc 90,90,90,200 -mh 20 -mp 10,850 -mf /usr/share/fonts/truetype/msttcorefonts/Trebuchet_MS.ttf -ht "`verse`"
imlibsetroot -x e -s /usr/share/archlinux/wallpaper/arch_paint_2_1920x1080.png

# update mouse pointer
#xsetroot -cursor_name left_ptr

# add directory to font path and reload cache
setxfont

# update keyboard settings
multikey

# start the gpg-agent
eval $(gpg-agent --daemon)

# display date information
display_date &
/usr/bin/dwm &

# start user programs
xsession

# start autostart programs
dex -a

wait %2
