#!/bin/bash
# dwm startup script

# extend the PATH variable with ~/bin
if [ -e "${HOME}/bin" ]; then
	export PATH="${HOME}/bin:${PATH}"
fi

export LANG=en_US.UTF-8
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus

# fix broken java applications
AWT_TOOLKIT=MToolkit;				export AWT_TOOLKIT
_JAVA_AWT_WM_NONREPARENTING=1;		export _JAVA_AWT_WM_NONREPARENTING

# set wallpaper
#display -window root $HOME/wallpaper0.jpg
#(DISPLAY=${DISPLAY}.1 display -window root $HOME/wallpaper1.jpg) &
#DISPLAY=${DISPLAY}.1 habak -hi $HOME/wallpaper1.jpg -mc 90,90,90,200 -mh 20 -mp 10,850 -mf /usr/share/fonts/truetype/msttcorefonts/Trebuchet_MS.ttf -ht "`verse`"
#habak -hi $HOME/wallpaper0.jpg -mc 90,90,90,200 -mh 20 -mp 10,850 -mf /usr/share/fonts/truetype/msttcorefonts/Trebuchet_MS.ttf -ht "`verse`"
# imlibsetroot -x e -s /usr/share/archlinux/wallpaper/arch_paint_2_1920x1080.png

# update mouse pointer
xsetroot -cursor_name left_ptr

# start the gpg-agent
if [ ! -e '/etc/X11/Xsession.d/90gpg-agent' ]; then
	eval $(gpg-agent --daemon)
fi

# start window manager
/usr/bin/dwm &

# start autostart programs
dex -a

wait %1
