#!/bin/bash
# Synchronize warp (https://github.com/mfaerevaag/wd) directory list with other
# tools
# Author: Jan Christoph Ebersbach <jceb@e-jc.de>
# Copyright: 2014, Jan Christoph Ebersbach
# License: Public Domain

if [[ ! -e ~/.warprc ]]; then
	echo "Unable to find file ~/.warprc" 1>&2
fi

# mc {{{1
if [[ ! -e ~/.config/mc/hotlist ]]; then
	mkdir -p ~/.config/mc
fi

while IFS=: read n l; do
	if [[ -z "${n}" ]] || [[ -z "${l}" ]]; then
		continue
	fi
	echo "ENTRY \"${n}\" URL \"${l}\""
done < ~/.warprc > ~/.config/mc/hotlist

# Spacefm, gtk {{{1
if [ -d ~/.config/spacefm ]; then
	while IFS=: read n l; do
		if [[ -z "${n}" ]] || [[ -z "${l}" ]]; then
			continue
		fi
		echo "file://${l} ${n}"
	done < ~/.warprc | tee ~/.config/spacefm/bookmarks | tee ~/.gtk-bookmarks >> ~/.config/gtk-3.0/bookmarks
	(cat ~/.config/gtk-3.0/bookmarks) | sort | uniq > ~/.config/gtk-3.0/bookmarks
fi


# CtrlP {{{1
if [ -d ~/.cache/ctrlp ]; then
	mkdir -p ~/.cache/ctrlp/bkd
	sed -e 's/:/\t/' < ~/.warprc > ~/.cache/ctrlp/bkd/cache.txt
fi

# ranger {{{1
sed -ne 's/^\([a-zA-Z0-9]\)[a-zA-Z0-9]*:\(.*\)/\1:\2/p' > ~/.config/ranger/bookmarks < ~/.warprc

# vi: ft=sh:tw=0:sw=4:ts=4:fdm=marker
