#!/bin/bash
# Synchronize warp (https://github.com/mfaerevaag/wd) directory list with other
# tools
# Author: Jan Christoph Ebersbach <jceb@e-jc.de>
# Copyright: 2014, Jan Christoph Ebersbach
# License: Public Domain

if [[ ! -e ~/.warprc ]]; then
	echo "Unable to find file ~/.warprc" 1>&2
fi

# mc {{{1
if [[ ! -e ~/.config/mc/hotlist ]]; then
	mkdir -p ~/.config/mc
fi

while IFS=: read n l; do
	if [[ -z "${n}" ]] || [[ -z "${l}" ]]; then
		continue
	fi
	echo "ENTRY \"${n}\" URL \"${l}\""
done < ~/.warprc > ~/.config/mc/hotlist

# Spacefm, gtk {{{1
if [ ! -d ~/.config/spacefm ]; then
	mkdir ~/.config/spacefm
fi
while IFS=: read n l; do
	if [[ -z "${n}" ]] || [[ -z "${l}" ]]; then
		continue
	fi
	echo "file://${l/ /%20} ${n}"
done < ~/.warprc | sort | uniq | tee ~/.config/spacefm/bookmarks | tee ~/.gtk-bookmarks > ~/.config/gtk-3.0/bookmarks


# CtrlP {{{1
if [ -d ~/.cache/ctrlp ]; then
	mkdir -p ~/.cache/ctrlp/bkd
	sed -e 's/:/\t/' < ~/.warprc > ~/.cache/ctrlp/bkd/cache.txt
fi

# Fuzzy Finder {{{1
if [ -d ~/.vim-fuf-data/bookmarkdir ]; then
	while IFS=: read n l; do
		if [[ -z "${n}" ]] || [[ -z "${l}" ]]; then
			continue
		fi
		echo "{'word': '${n}', 'path': '${l}', 'time': '$(date +%s)'}"
	done < ~/.warprc > ~/.vim-fuf-data/bookmarkdir/items
fi

# ranger {{{1
sed -ne 's/^\([a-zA-Z0-9]\)[a-zA-Z0-9]*:\(.*\)/\1:\2/p' > ~/.config/ranger/bookmarks < ~/.warprc

# KDE {{{1
# ~/.local/share/user-places.xbel

# vi: ft=sh:tw=0:sw=4:ts=4:fdm=marker
