#!/bin/bash
# extract URLs from current tmux pane, select one via fzf and copy it into
# clipboard
# set -x
set -e
set -u
set -o pipefail

if [[ -z "${TMUX}" ]]; then
    echo "Error: tmux isn't running." 1>&2
    exit 1
fi

regexp_url='[[:alnum:]]+:///?[^[:space:]]+[^][()⟩{}:[:space:]]'
regexp_file='([-~_./[:alnum:]]+/[-_./[:alnum:]]*|[-_.[:alnum:]]+\.[-_[:alnum:]]+)'

if [[ $# -ge 1 ]] && ([[ "$1" = "-f" ]] || [[ "$1" = "-F" ]]); then
    # capture everything in this pane instead of only the visible part
    # -S -
    prompt='Copy filename'
    cmd=(xsel -i)
    if [[ "$1" = "-F" ]]; then
        prompt='Paste filename'
        cmd=(tmux load-buffer -)
    fi
    set +e
    (tmux capture-pane && tmux save-buffer - | grep -o -E "${regexp_file}" | grep -v -E "${regexp_url}" | sort | uniq | dmenu -i -l 10 -p "${prompt}" | tr -d '\n' | "${cmd[@]}") 2>/dev/null
    if [[ $? -eq 0 ]] && [[ "$1" = "-F" ]]; then
        tmux paste-buffer
    fi
    set -e
elif [[ $# -ge 1 ]] && ([[ "$1" = "-u" ]] || [[ "$1" = "-U" ]]); then
    prompt='Copy URL'
    cmd=(xsel -i)
    if [[ "$1" = "-U" ]]; then
        prompt='Open URL'
        cmd=(xargs xdg-open)
    fi
    (tmux capture-pane && tmux save-buffer - | xurls | sort | uniq | dmenu -i -l 10 -p "${prompt}" | tr -d '\n' | "${cmd[@]}") &>/dev/null || true
fi
