#!/bin/bash
# extract URLs from current tmux pane, select one via fzf and copy it into
# clipboard
# set -x
set -e
set -u

if [[ -z "${TMUX}" ]]; then
    echo "Error: tmux isn't running." 1>&2
    exit 1
fi

regexp_url='[[:alnum:]]+:///?[^[:space:]]+[^][()⟩{}:[:space:]]'
regexp_file='([-_./[:alnum:]]+/[-_./[:alnum:]]*|[-_.[:alnum:]]+\.[-_[:alnum:]]+)'

if [[ $# -ge 1 ]] && [[ "$1" = "-f" ]]; then
    # capture everything in this pane instead of only the visible part
    # -S -
    (tmux capture-pane && tmux save-buffer - | grep -o -E "${regexp_file}" | grep -v -E "${regexp_url}" | sort | uniq | dmenu -l 10 | tr -d '\n' | xsel -i) &>/dev/null || true
elif [[ $# -ge 1 ]] && [[ "$1" = "-F" ]]; then
    if [[ $# -ge 2 ]]; then
        cd "${2}"
        # :
    fi
    # tmux split-window bash
    if [[ -n "${FZF_DEFAULT_COMMAND}" ]]; then
        # (eval "${FZF_DEFAULT_COMMAND}" | FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} -0" fzf-tmux -d"${FZF_TMUX_HEIGHT:-40%}" | tr -d '\n' | xsel -i) &>/dev/null
        (FZF_DEFAULT_COMMAND="${FZF_DEFAULT_COMMAND}" FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} -0" fzf-tmux -d"${FZF_TMUX_HEIGHT:-40%}" | tr -d '\n' | xsel -i) &>/dev/null || true
    else
        (FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} -0" fzf-tmux -d"${FZF_TMUX_HEIGHT:-40%}" | tr -d '\n' | xsel -i) &>/dev/null || true
    fi
elif [[ $# -ge 1 ]] && ([[ "$1" = "-u" ]] || [[ "$1" = "-U" ]]); then
    prompt='Copy URL'
    cmd=(xsel -i)
    if [[ "$1" = "-U" ]]; then
        prompt='Open URL'
        cmd=(xargs xdg-open)
    fi
    (tmux capture-pane && tmux save-buffer - | xurls | sort | uniq | dmenu -l 10 -p "${prompt}" | tr -d '\n' | "${cmd[@]}") &>/dev/null || true
fi
