#!/bin/sh
synclient \
    VertEdgeScroll=1 \
    HorizEdgeScroll=0 \
    CornerCoasting=1 \
    VertTwoFingerScroll=0 \
    HorizTwoFingerScroll=1 \
    UpDownScrolling=1 \
    LeftRightScrolling=1 \
    UpDownScrollRepeat=1 \
    LeftRightScrollRepeat=1 \
    TouchpadOff=0 \
    GuestMouseOff=0 \
    TapButton1=1 \
    TapButton2=2 \
    TapButton3=3 \
    ClickFinger1=1 \
    ClickFinger2=1 \
    ClickFinger3=2

xsetroot -cursor_name left_ptr
