#!/bin/sh
synclient \
    VertEdgeScroll=1 \
    HorizEdgeScroll=0 \
    CornerCoasting=1 \
    VertTwoFingerScroll=1 \
    HorizTwoFingerScroll=1 \
    TouchpadOff=0 \
    TapButton1=1 \
    TapButton2=2 \
    TapButton3=3 \
    ClickFinger1=1 \
    ClickFinger2=1 \
    ClickFinger3=2 \
    PalmDetect=1 \
    MaxTapMove=530

xsetroot -cursor_name left_ptr
