#!/usr/bin/python
# -*- coding: utf-8 -*-
# vio
#  Opens a file in a running vim instance
#
# Depends: vim
#
# Copyright (C) 2011 Jan Christoph Ebersbach
#
# http://www.e-jc.de/
#
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Binary versions of this file provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
# USA

import sys
import os
import subprocess

editor = os.environ['EDITOR']
if not editor:
	editor = 'vim'

servername = os.path.basename(os.getcwd())
if not servername:
	servername = 'vim'

def get_servername(default_servername):
	_servername = raw_input('Enter a server name? [%s] ' % default_servername).strip()
	if _servername == '':
		_servername = default_servername
	return _servername

def exec_vim(args):
	os.execv(editor, ['vim'] + args)

if __name__ == '__main__':
	try:
		if len(sys.argv) == 1:
			exec_vim(['--servername', get_servername(servername)])
		else:
			args = sys.argv[1:]
			# build server list
			p = subprocess.Popen([editor, '--serverlist'], stdout=subprocess.PIPE)
			serverlist = [ i  for i in p.communicate()[0].strip().split('\n') if i.strip() != '' ]

			if len(serverlist):
				for i, server in enumerate(serverlist):
					print '%2d. %s' % (i+1, server)
				print '%2d. %s' % (len(serverlist) + 1, 'Start a new server ..')
				res = raw_input('Which one? [1. %s] ' % serverlist[0])
				try:
					if res == '':
						res = 0
					else:
						res = int(res) - 1
				except ValueError, e:
					print 'Failed to convert input to number.'

				_servername = []
				if res == len(serverlist):
					_servername.append(get_servername(servername))
				elif res < 0 or res >= len(serverlist):
					print 'Number out of range.'
				else:
					_servername.append(serverlist[res])
					_servername.append('--remote')
				exec_vim(['--servername'] + _servername + args)
			else:
				exec_vim(['--servername', get_servername(servername)] + args)
	except EOFError:
		pass
	except KeyboardInterrupt:
		pass
