#!/bin/sh
# Script for selecting a vim server using dmenu
# Author: Jan Christoph Ebersbach <jceb@e-jc.de>
# Last Modified: Sat 08. Jun 2013 14:46:33 +0200 CEST
set -e
server="$(vim --serverlist | dmenu)"
if [ -n "${server}" ]; then
	vim=gvim
	if [ -n "${TERM}" ] && [ "${TERM}" != "dumb" ]; then
		vim=vim
	fi
	"${vim}" --servername "${server}" --remote "$@" "${TERM}"
fi
