#!/bin/bash
# open files in a vim server

set -e
set -u

GLOBAL=
if [ "$(basename "$0")" = "gserver" ]; then
	GLOBAL="-g"
fi

# enforce editor to make it work better with tmux and ranger
if [ -n "${GLOBAL}" ]; then
	EDITOR="${REALEDITOR:=/usr/bin/gvim}"
else
	EDITOR="${REALEDITOR:=/usr/bin/vim}"
fi

cmd=("${EDITOR}")

if [ $# -ge 1 ]; then
	cmd+=(--servername "$(vsession "${GLOBAL}")")
	if [ "${1:0:1}" != "-" ]; then
		cmd+=(--remote-silent)
	fi
	cmd+=("$@")
else
	cmd+=(--servername "$(vsession "${GLOBAL}")")
fi
exec "${cmd[@]}"
