#!/bin/sh
# Script for selecting a vim server using dmenu
# Author: Jan Christoph Ebersbach <jceb@e-jc.de>
# Last Modified: Mon 10. Jun 2013 15:56:21 +0200 CEST
set -e
server="$(vsession -n)"
if [ -n "${server}" ]; then
	vim=gvim
	if [ -n "${TERM}" ] && [ "${TERM}" != "dumb" ]; then
		vim=vim
	fi
	/usr/bin/"${vim}" --servername "${server}" --remote-silent "$@"
fi
