#!/bin/sh
# Rust regex: https://doc.rust-lang.org/regex/regex/index.html
command rg -e '[A-Za-z]+:///?[^/\s:]+(:[0-9]+)?(/([^\s]*[^])}."\047])?)?' -e '(www.[^/\s]+\.[^/\s]+|localhost)(:[0-9]+)?(/([^\s]*[^])}."\047])?)?' "$@"
